### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [Sefaria/BetaMidrash#4]
Shavua tow,

would you mind adding the `.apk` to the release page here at Github (see: [Creating Releases](https://help.github.com/articles/creating-releases/) on the Github help pages for how to do that, it's quite easy and painless), so folks without Playstore access can join in learning? I could then also add it to [my F-Droid compatible repo](https://android.izzysoft.de/repo) to allow for automatic updates.

Thanks in advance,
Izzy.

**Comment by betamidrash** [comment]
Thank you for the recommendation.

The current release is now on 
https://github.com/Sefaria/Sefaria-Android/releases/tag/3.01

Thank you.

Let us know if anything else comes to mind.

**Comment by IzzySoft** [comment]
Todah rabbah! Just added it to my repo (as promised) plus my app lists for Judaica (section [Talmud & Co.](https://android.izzysoft.de/applists/category/named/religion_judaism#group_622)). If you release a new version and add the APK to it again, the repo will be updated automatically (usually within 24h). Feel free to point users to the repo if they cannot (or don't want to) use the Playstore.

> Let us know if anything else comes to mind.

You might want to point out on your Github front-page (aka `README.md`) where to find the app. Not everyone digs for the `Manifest` to find the package name and check it against app stores – and many are "scared away" if they think they need to install a development suite :)

Thanks again, and keep up the good work!

**Comment by IzzySoft** [comment]
Guess this can be closed now. Big thanks again!

**Comment by IzzySoft** [comment]
@betamidrash are you still maintaining this app? Got quite calm here.

**Comment by nsantacruz** [comment]
@IzzySoft nope! It hasn't been maintained in a few years. The new app repo is here: https://github.com/Sefaria/Sefaria-iOS. The repo name is `Sefaria-iOS` but it actually has the code for both Android and iOS

**Comment by IzzySoft** [comment]
Thanks! Looking forward to the first release there then.

**Comment by IzzySoft** [comment]
@nsantacruz may I ask where to find the APKs there? Still no releases tagged – but the app is on Play Store (last updated 5 days ago). For a while they've been [here](https://github.com/Sefaria/Sefaria-Android) – but that points to Sefaria/Sefaria-iOS for "further releases" which aren't there.
